n = input('digite algo: ')
print('é alfabetico?', n.isalpha())
print('é numero?', n.isnumeric())
print('é alfa numerico?', n.isalnum())
print('é só espaços?', n.isspace())
print('é um decimal?', n.isdecimal())
print('é um digito?', n.isdigit())
print('é minusculas?', n.islower())
print('é maiúsculas?', n.isupper())
print('esta capitalizada?', n.istitle())
